apiVersion: v1
kind: Service
metadata:
  labels:
    app: usermicroservice
  name: user-service
spec:
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
  selector:
    app: usermicroservice
  type: LoadBalancer
status:
  loadBalancer: {}
